/**
 * PET B1 Preliminary Vocabulary Data
 * Based on Cambridge Official B1 Preliminary Vocabulary List (2025 Edition)
 * L1 - 基础必备词汇 (~300 words), organized by topic
 * Each entry: id, word, phonetic_uk, phonetic_us, meaning, pos, example_en, example_zh, topic, level
 */
const PET_VOCABULARY = [
  // ================================================================
  // 1. CLOTHING & ACCESSORIES (服饰与配饰) - ~20 words
  // ================================================================
  {id:"pet_001",word:"backpack",phonetic_uk:"/ˈbæk.pæk/",phonetic_us:"/ˈbæk.pæk/",meaning:"背包；双肩包",pos:"noun",example_en:"I put my books in my backpack.",example_zh:"我把书放进背包里。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_002",word:"blouse",phonetic_uk:"/blaʊz/",phonetic_us:"/blaʊs/",meaning:"女式衬衫",pos:"noun",example_en:"She wore a white blouse to the interview.",example_zh:"她穿了一件白衬衫去面试。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_003",word:"boot",phonetic_uk:"/buːt/",phonetic_us:"/buːt/",meaning:"靴子",pos:"noun",example_en:"I need new boots for the winter.",example_zh:"我需要一双冬天穿的新靴子。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_004",word:"bracelet",phonetic_uk:"/ˈbreɪs.lət/",phonetic_us:"/ˈbreɪs.lət/",meaning:"手镯；手链",pos:"noun",example_en:"She received a silver bracelet for her birthday.",example_zh:"她生日时收到了一条银手链。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_005",word:"button",phonetic_uk:"/ˈbʌt.ən/",phonetic_us:"/ˈbʌt̬.ən/",meaning:"纽扣；按钮",pos:"noun",example_en:"One button is missing from my shirt.",example_zh:"我衬衫上掉了一颗纽扣。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_006",word:"casual",phonetic_uk:"/ˈkæʒ.u.əl/",phonetic_us:"/ˈkæʒ.u.əl/",meaning:"休闲的；随意的",pos:"adj",example_en:"We can wear casual clothes on Fridays.",example_zh:"周五我们可以穿休闲装。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_007",word:"coat",phonetic_uk:"/kəʊt/",phonetic_us:"/koʊt/",meaning:"外套；大衣",pos:"noun",example_en:"Take a coat, it's cold outside.",example_zh:"带件外套，外面冷。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_008",word:"cotton",phonetic_uk:"/ˈkɒt.ən/",phonetic_us:"/ˈkɑː.t̬ən/",meaning:"棉；棉布",pos:"noun",example_en:"This shirt is made of cotton.",example_zh:"这件衬衫是棉质的。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_009",word:"fashion",phonetic_uk:"/ˈfæʃ.ən/",phonetic_us:"/ˈfæʃ.ən/",meaning:"时尚；时装",pos:"noun",example_en:"She is very interested in fashion.",example_zh:"她对时尚非常感兴趣。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_010",word:"glove",phonetic_uk:"/ɡlʌv/",phonetic_us:"/ɡlʌv/",meaning:"手套",pos:"noun",example_en:"I wear gloves to keep my hands warm.",example_zh:"我戴手套让手保持温暖。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_011",word:"hoodie",phonetic_uk:"/ˈhʊd.i/",phonetic_us:"/ˈhʊd.i/",meaning:"连帽衫",pos:"noun",example_en:"He always wears a hoodie to school.",example_zh:"他总是穿连帽衫去上学。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_012",word:"jacket",phonetic_uk:"/ˈdʒæk.ɪt/",phonetic_us:"/ˈdʒæk.ɪt/",meaning:"夹克；短上衣",pos:"noun",example_en:"I bought a new jacket for autumn.",example_zh:"我为秋天买了一件新夹克。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_013",word:"jewellery",phonetic_uk:"/ˈdʒuː.əl.ri/",phonetic_us:"/ˈdʒuː.əl.ri/",meaning:"珠宝；首饰",pos:"noun",example_en:"She keeps her jewellery in a small box.",example_zh:"她把首饰放在一个小盒子里。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_014",word:"pocket",phonetic_uk:"/ˈpɒk.ɪt/",phonetic_us:"/ˈpɑː.kɪt/",meaning:"口袋",pos:"noun",example_en:"He put the keys in his pocket.",example_zh:"他把钥匙放进了口袋。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_015",word:"scarf",phonetic_uk:"/skɑːf/",phonetic_us:"/skɑːrf/",meaning:"围巾",pos:"noun",example_en:"She wore a warm scarf around her neck.",example_zh:"她脖子上围了一条暖和的围巾。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_016",word:"shorts",phonetic_uk:"/ʃɔːts/",phonetic_us:"/ʃɔːrts/",meaning:"短裤",pos:"noun",example_en:"It's hot today, so I'm wearing shorts.",example_zh:"今天很热，所以我穿了短裤。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_017",word:"suit",phonetic_uk:"/suːt/",phonetic_us:"/suːt/",meaning:"套装；西服",pos:"noun",example_en:"He wore a suit to the wedding.",example_zh:"他穿了一套西装去参加婚礼。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_018",word:"sweater",phonetic_uk:"/ˈswet.ər/",phonetic_us:"/ˈswet̬.ər/",meaning:"毛衣",pos:"noun",example_en:"My grandmother knitted this sweater for me.",example_zh:"这件毛衣是我奶奶织给我的。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_019",word:"trainers",phonetic_uk:"/ˈtreɪ.nəz/",phonetic_us:"/ˈtreɪ.nɚz/",meaning:"运动鞋",pos:"noun",example_en:"I need new trainers for PE class.",example_zh:"我需要一双新的运动鞋上体育课。",topic:"服饰与配饰",level:"L1"},
  {id:"pet_020",word:"uniform",phonetic_uk:"/ˈjuː.nɪ.fɔːm/",phonetic_us:"/ˈjuː.nə.fɔːrm/",meaning:"制服",pos:"noun",example_en:"Students must wear a uniform at our school.",example_zh:"我们学校的学生必须穿校服。",topic:"服饰与配饰",level:"L1"},

  // ================================================================
  // 2. COMMUNICATION & TECHNOLOGY (通讯与科技) - ~25 words
  // ================================================================
  {id:"pet_021",word:"app",phonetic_uk:"/æp/",phonetic_us:"/æp/",meaning:"应用程序",pos:"noun",example_en:"I downloaded a new app for learning English.",example_zh:"我下载了一个学英语的新应用。",topic:"通讯与科技",level:"L1"},
  {id:"pet_022",word:"blog",phonetic_uk:"/blɒɡ/",phonetic_us:"/blɑːɡ/",meaning:"博客",pos:"noun",example_en:"She writes a blog about travelling.",example_zh:"她写了一个关于旅行的博客。",topic:"通讯与科技",level:"L1"},
  {id:"pet_023",word:"cable",phonetic_uk:"/ˈkeɪ.bəl/",phonetic_us:"/ˈkeɪ.bəl/",meaning:"电缆；电线",pos:"noun",example_en:"I need a longer cable to charge my phone.",example_zh:"我需要一根更长的数据线给手机充电。",topic:"通讯与科技",level:"L1"},
  {id:"pet_024",word:"cell phone",phonetic_uk:"/ˈsel fəʊn/",phonetic_us:"/ˈsel foʊn/",meaning:"手机",pos:"noun",example_en:"I left my cell phone at home.",example_zh:"我把手机忘在家里了。",topic:"通讯与科技",level:"L1"},
  {id:"pet_025",word:"channel",phonetic_uk:"/ˈtʃæn.əl/",phonetic_us:"/ˈtʃæn.əl/",meaning:"频道；渠道",pos:"noun",example_en:"Which channel is the match on?",example_zh:"比赛在哪个频道？",topic:"通讯与科技",level:"L1"},
  {id:"pet_026",word:"click",phonetic_uk:"/klɪk/",phonetic_us:"/klɪk/",meaning:"点击；单击",pos:"verb",example_en:"Click the button to start the download.",example_zh:"点击按钮开始下载。",topic:"通讯与科技",level:"L1"},
  {id:"pet_027",word:"computer",phonetic_uk:"/kəmˈpjuː.tər/",phonetic_us:"/kəmˈpjuː.t̬ɚ/",meaning:"电脑；计算机",pos:"noun",example_en:"I use my computer for homework every day.",example_zh:"我每天用电脑做作业。",topic:"通讯与科技",level:"L1"},
  {id:"pet_028",word:"connect",phonetic_uk:"/kəˈnekt/",phonetic_us:"/kəˈnekt/",meaning:"连接",pos:"verb",example_en:"I can't connect to the Wi-Fi.",example_zh:"我连不上Wi-Fi。",topic:"通讯与科技",level:"L1"},
  {id:"pet_029",word:"download",phonetic_uk:"/ˌdaʊnˈləʊd/",phonetic_us:"/ˈdaʊn.loʊd/",meaning:"下载",pos:"verb",example_en:"You can download the file from the website.",example_zh:"你可以从网站下载这个文件。",topic:"通讯与科技",level:"L1"},
  {id:"pet_030",word:"electronic",phonetic_uk:"/ɪˌlekˈtrɒn.ɪk/",phonetic_us:"/ɪˌlekˈtrɑː.nɪk/",meaning:"电子的",pos:"adj",example_en:"Electronic devices are not allowed during the exam.",example_zh:"考试期间不允许使用电子设备。",topic:"通讯与科技",level:"L1"},
  {id:"pet_031",word:"email",phonetic_uk:"/ˈiː.meɪl/",phonetic_us:"/ˈiː.meɪl/",meaning:"电子邮件",pos:"noun",example_en:"I sent you an email with the details.",example_zh:"我发了一封邮件给你，里面有详细信息。",topic:"通讯与科技",level:"L1"},
  {id:"pet_032",word:"headphones",phonetic_uk:"/ˈhed.fəʊnz/",phonetic_us:"/ˈhed.foʊnz/",meaning:"耳机",pos:"noun",example_en:"I listen to music with my headphones.",example_zh:"我用耳机听音乐。",topic:"通讯与科技",level:"L1"},
  {id:"pet_033",word:"keyboard",phonetic_uk:"/ˈkiː.bɔːd/",phonetic_us:"/ˈkiː.bɔːrd/",meaning:"键盘",pos:"noun",example_en:"I need a new keyboard for my computer.",example_zh:"我需要一个新的电脑键盘。",topic:"通讯与科技",level:"L1"},
  {id:"pet_034",word:"laptop",phonetic_uk:"/ˈlæp.tɒp/",phonetic_us:"/ˈlæp.tɑːp/",meaning:"笔记本电脑",pos:"noun",example_en:"She takes her laptop to school every day.",example_zh:"她每天带笔记本电脑去上学。",topic:"通讯与科技",level:"L1"},
  {id:"pet_035",word:"message",phonetic_uk:"/ˈmes.ɪdʒ/",phonetic_us:"/ˈmes.ɪdʒ/",meaning:"消息；信息",pos:"noun",example_en:"I got a message from my friend.",example_zh:"我收到了朋友的一条消息。",topic:"通讯与科技",level:"L1"},
  {id:"pet_036",word:"online",phonetic_uk:"/ˈɒn.laɪn/",phonetic_us:"/ˈɑːn.laɪn/",meaning:"在线的",pos:"adj",example_en:"We do online classes every Monday.",example_zh:"我们每周一上网课。",topic:"通讯与科技",level:"L1"},
  {id:"pet_037",word:"password",phonetic_uk:"/ˈpɑːs.wɜːd/",phonetic_us:"/ˈpæs.wɝːd/",meaning:"密码",pos:"noun",example_en:"Don't share your password with anyone.",example_zh:"不要把你的密码告诉任何人。",topic:"通讯与科技",level:"L1"},
  {id:"pet_038",word:"printer",phonetic_uk:"/ˈprɪn.tər/",phonetic_us:"/ˈprɪn.t̬ɚ/",meaning:"打印机",pos:"noun",example_en:"The printer is out of paper.",example_zh:"打印机没有纸了。",topic:"通讯与科技",level:"L1"},
  {id:"pet_039",word:"screen",phonetic_uk:"/skriːn/",phonetic_us:"/skriːn/",meaning:"屏幕",pos:"noun",example_en:"Don't look at the screen for too long.",example_zh:"不要盯着屏幕看太久。",topic:"通讯与科技",level:"L1"},
  {id:"pet_040",word:"search",phonetic_uk:"/sɜːtʃ/",phonetic_us:"/sɝːtʃ/",meaning:"搜索",pos:"verb",example_en:"I searched for the information online.",example_zh:"我在网上搜索了信息。",topic:"通讯与科技",level:"L1"},
  {id:"pet_041",word:"smartphone",phonetic_uk:"/ˈsmɑːt.fəʊn/",phonetic_us:"/ˈsmɑːrt.foʊn/",meaning:"智能手机",pos:"noun",example_en:"Most teenagers have a smartphone.",example_zh:"大多数青少年都有智能手机。",topic:"通讯与科技",level:"L1"},
  {id:"pet_042",word:"social media",phonetic_uk:"/ˌsəʊ.ʃəl ˈmiː.di.ə/",phonetic_us:"/ˌsoʊ.ʃəl ˈmiː.di.ə/",meaning:"社交媒体",pos:"noun",example_en:"She spends too much time on social media.",example_zh:"她在社交媒体上花了太多时间。",topic:"通讯与科技",level:"L1"},
  {id:"pet_043",word:"software",phonetic_uk:"/ˈsɒft.weər/",phonetic_us:"/ˈsɑːft.wer/",meaning:"软件",pos:"noun",example_en:"You need to update the software.",example_zh:"你需要更新一下软件。",topic:"通讯与科技",level:"L1"},
  {id:"pet_044",word:"text",phonetic_uk:"/tekst/",phonetic_us:"/tekst/",meaning:"短信；文字",pos:"noun",example_en:"She sent me a text to confirm the time.",example_zh:"她给我发了条短信确认时间。",topic:"通讯与科技",level:"L1"},
  {id:"pet_045",word:"website",phonetic_uk:"/ˈweb.saɪt/",phonetic_us:"/ˈweb.saɪt/",meaning:"网站",pos:"noun",example_en:"The school website has all the information.",example_zh:"学校网站上有所有信息。",topic:"通讯与科技",level:"L1"},

  // ================================================================
  // 3. EDUCATION (教育) - ~25 words
  // ================================================================
  {id:"pet_046",word:"achievement",phonetic_uk:"/əˈtʃiːv.mənt/",phonetic_us:"/əˈtʃiːv.mənt/",meaning:"成就；成绩",pos:"noun",example_en:"Winning the competition was a great achievement.",example_zh:"赢得比赛是一个很大的成就。",topic:"教育",level:"L1"},
  {id:"pet_047",word:"article",phonetic_uk:"/ˈɑː.tɪ.kəl/",phonetic_us:"/ˈɑːr.t̬ɪ.kəl/",meaning:"文章",pos:"noun",example_en:"I read an interesting article about space.",example_zh:"我读了一篇关于太空的有趣文章。",topic:"教育",level:"L1"},
  {id:"pet_048",word:"beginner",phonetic_uk:"/bɪˈɡɪn.ər/",phonetic_us:"/bɪˈɡɪn.ɚ/",meaning:"初学者",pos:"noun",example_en:"The course is designed for beginners.",example_zh:"这门课是为初学者设计的。",topic:"教育",level:"L1"},
  {id:"pet_049",word:"biology",phonetic_uk:"/baɪˈɒl.ə.dʒi/",phonetic_us:"/baɪˈɑː.lə.dʒi/",meaning:"生物",pos:"noun",example_en:"Biology is my favourite subject.",example_zh:"生物是我最喜欢的科目。",topic:"教育",level:"L1"},
  {id:"pet_050",word:"certificate",phonetic_uk:"/səˈtɪf.ɪ.kət/",phonetic_us:"/sɚˈtɪf.ə.kət/",meaning:"证书；证明",pos:"noun",example_en:"I received a certificate for completing the course.",example_zh:"我获得了完成课程的证书。",topic:"教育",level:"L1"},
  {id:"pet_051",word:"chemistry",phonetic_uk:"/ˈkem.ɪ.stri/",phonetic_us:"/ˈkem.ɪ.stri/",meaning:"化学",pos:"noun",example_en:"We do experiments in chemistry class.",example_zh:"我们在化学课上做实验。",topic:"教育",level:"L1"},
  {id:"pet_052",word:"classmate",phonetic_uk:"/ˈklɑːs.meɪt/",phonetic_us:"/ˈklæs.meɪt/",meaning:"同学",pos:"noun",example_en:"My classmates helped me with the project.",example_zh:"我的同学帮我做了这个项目。",topic:"教育",level:"L1"},
  {id:"pet_053",word:"classroom",phonetic_uk:"/ˈklɑːs.ruːm/",phonetic_us:"/ˈklæs.ruːm/",meaning:"教室",pos:"noun",example_en:"The classroom was quiet during the test.",example_zh:"考试时教室里很安静。",topic:"教育",level:"L1"},
  {id:"pet_054",word:"college",phonetic_uk:"/ˈkɒl.ɪdʒ/",phonetic_us:"/ˈkɑː.lɪdʒ/",meaning:"学院；大学",pos:"noun",example_en:"She wants to go to college to study art.",example_zh:"她想上大学学艺术。",topic:"教育",level:"L1"},
  {id:"pet_055",word:"course",phonetic_uk:"/kɔːs/",phonetic_us:"/kɔːrs/",meaning:"课程",pos:"noun",example_en:"I'm taking a course in computer programming.",example_zh:"我在上一门计算机编程课。",topic:"教育",level:"L1"},
  {id:"pet_056",word:"degree",phonetic_uk:"/dɪˈɡriː/",phonetic_us:"/dɪˈɡriː/",meaning:"学位；程度",pos:"noun",example_en:"He has a degree in engineering.",example_zh:"他有工程学学位。",topic:"教育",level:"L1"},
  {id:"pet_057",word:"education",phonetic_uk:"/ˌedʒ.uˈkeɪ.ʃən/",phonetic_us:"/ˌedʒ.əˈkeɪ.ʃən/",meaning:"教育",pos:"noun",example_en:"Education is important for everyone.",example_zh:"教育对每个人都很重要。",topic:"教育",level:"L1"},
  {id:"pet_058",word:"essay",phonetic_uk:"/ˈes.eɪ/",phonetic_us:"/ˈes.eɪ/",meaning:"短文；作文",pos:"noun",example_en:"I have to write an essay about pollution.",example_zh:"我得写一篇关于污染的短文。",topic:"教育",level:"L1"},
  {id:"pet_059",word:"exam",phonetic_uk:"/ɪɡˈzæm/",phonetic_us:"/ɪɡˈzæm/",meaning:"考试",pos:"noun",example_en:"I'm studying hard for the English exam.",example_zh:"我正在努力备考英语考试。",topic:"教育",level:"L1"},
  {id:"pet_060",word:"geography",phonetic_uk:"/dʒiˈɒɡ.rə.fi/",phonetic_us:"/dʒiˈɑː.ɡrə.fi/",meaning:"地理",pos:"noun",example_en:"In geography we learn about different countries.",example_zh:"在地理课上我们学习不同的国家。",topic:"教育",level:"L1"},
  {id:"pet_061",word:"history",phonetic_uk:"/ˈhɪs.tər.i/",phonetic_us:"/ˈhɪs.t̬ɚ.i/",meaning:"历史",pos:"noun",example_en:"History helps us understand the past.",example_zh:"历史帮助我们了解过去。",topic:"教育",level:"L1"},
  {id:"pet_062",word:"homework",phonetic_uk:"/ˈhəʊm.wɜːk/",phonetic_us:"/ˈhoʊm.wɝːk/",meaning:"家庭作业",pos:"noun",example_en:"I have a lot of homework tonight.",example_zh:"今晚我有很多家庭作业。",topic:"教育",level:"L1"},
  {id:"pet_063",word:"knowledge",phonetic_uk:"/ˈnɒl.ɪdʒ/",phonetic_us:"/ˈnɑː.lɪdʒ/",meaning:"知识",pos:"noun",example_en:"Reading books increases your knowledge.",example_zh:"读书增长知识。",topic:"教育",level:"L1"},
  {id:"pet_064",word:"laboratory",phonetic_uk:"/ləˈbɒr.ə.tər.i/",phonetic_us:"/ˈlæb.rə.tɔːr.i/",meaning:"实验室",pos:"noun",example_en:"We did an experiment in the science laboratory.",example_zh:"我们在科学实验室做了一个实验。",topic:"教育",level:"L1"},
  {id:"pet_065",word:"language",phonetic_uk:"/ˈlæŋ.ɡwɪdʒ/",phonetic_us:"/ˈlæŋ.ɡwɪdʒ/",meaning:"语言",pos:"noun",example_en:"Learning a new language takes time.",example_zh:"学一门新语言需要时间。",topic:"教育",level:"L1"},
  {id:"pet_066",word:"mark",phonetic_uk:"/mɑːk/",phonetic_us:"/mɑːrk/",meaning:"分数；成绩",pos:"noun",example_en:"I got a good mark on my maths test.",example_zh:"我数学测验得了好分数。",topic:"教育",level:"L1"},
  {id:"pet_067",word:"notebook",phonetic_uk:"/ˈnəʊt.bʊk/",phonetic_us:"/ˈnoʊt.bʊk/",meaning:"笔记本",pos:"noun",example_en:"I write new words in my notebook.",example_zh:"我把生词写在笔记本上。",topic:"教育",level:"L1"},
  {id:"pet_068",word:"project",phonetic_uk:"/ˈprɒdʒ.ekt/",phonetic_us:"/ˈprɑː.dʒekt/",meaning:"项目；课题",pos:"noun",example_en:"Our group is working on a science project.",example_zh:"我们组正在做一个科学项目。",topic:"教育",level:"L1"},
  {id:"pet_069",word:"qualification",phonetic_uk:"/ˌkwɒl.ɪ.fɪˈkeɪ.ʃən/",phonetic_us:"/ˌkwɑː.lə.fəˈkeɪ.ʃən/",meaning:"资格证书；学历",pos:"noun",example_en:"Good qualifications help you find a job.",example_zh:"好的学历有助于你找工作。",topic:"教育",level:"L1"},
  {id:"pet_070",word:"textbook",phonetic_uk:"/ˈtekst.bʊk/",phonetic_us:"/ˈtekst.bʊk/",meaning:"课本；教科书",pos:"noun",example_en:"Please open your textbook to page 50.",example_zh:"请打开课本第50页。",topic:"教育",level:"L1"},

  // ================================================================
  // 4. ENTERTAINMENT & MEDIA (娱乐与媒体) - ~25 words
  // ================================================================
  {id:"pet_071",word:"adventure",phonetic_uk:"/ədˈven.tʃər/",phonetic_us:"/ədˈven.tʃɚ/",meaning:"冒险；奇遇",pos:"noun",example_en:"The story is about an exciting adventure.",example_zh:"这个故事是关于一次激动人心的冒险。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_072",word:"audience",phonetic_uk:"/ˈɔː.di.əns/",phonetic_us:"/ˈɑː.di.əns/",meaning:"观众；听众",pos:"noun",example_en:"The audience clapped at the end.",example_zh:"演出结束时观众鼓掌了。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_073",word:"cartoon",phonetic_uk:"/kɑːˈtuːn/",phonetic_us:"/kɑːrˈtuːn/",meaning:"动画片；漫画",pos:"noun",example_en:"My little brother loves watching cartoons.",example_zh:"我弟弟喜欢看动画片。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_074",word:"chat show",phonetic_uk:"/ˈtʃæt ʃəʊ/",phonetic_us:"/ˈtʃæt ʃoʊ/",meaning:"访谈节目",pos:"noun",example_en:"The famous actor appeared on a chat show.",example_zh:"这位著名演员上了一个访谈节目。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_075",word:"comedy",phonetic_uk:"/ˈkɒm.ə.di/",phonetic_us:"/ˈkɑː.mə.di/",meaning:"喜剧",pos:"noun",example_en:"We watched a comedy and laughed a lot.",example_zh:"我们看了一部喜剧，笑得很开心。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_076",word:"concert",phonetic_uk:"/ˈkɒn.sət/",phonetic_us:"/ˈkɑːn.sɚt/",meaning:"音乐会",pos:"noun",example_en:"We went to a rock concert last Saturday.",example_zh:"上周六我们去了一场摇滚音乐会。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_077",word:"documentary",phonetic_uk:"/ˌdɒk.jəˈmen.tər.i/",phonetic_us:"/ˌdɑː.kjəˈmen.t̬ɚ.i/",meaning:"纪录片",pos:"noun",example_en:"I watched a documentary about whales.",example_zh:"我看了一部关于鲸鱼的纪录片。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_078",word:"drama",phonetic_uk:"/ˈdrɑː.mə/",phonetic_us:"/ˈdræm.ə/",meaning:"戏剧",pos:"noun",example_en:"She is studying drama at school.",example_zh:"她在学校学戏剧。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_079",word:"exhibition",phonetic_uk:"/ˌek.sɪˈbɪʃ.ən/",phonetic_us:"/ˌek.səˈbɪʃ.ən/",meaning:"展览",pos:"noun",example_en:"There's an art exhibition at the museum.",example_zh:"博物馆有一个艺术展览。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_080",word:"festival",phonetic_uk:"/ˈfes.tɪ.vəl/",phonetic_us:"/ˈfes.tə.vəl/",meaning:"节日；节庆",pos:"noun",example_en:"The music festival lasts for three days.",example_zh:"音乐节持续三天。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_081",word:"film",phonetic_uk:"/fɪlm/",phonetic_us:"/fɪlm/",meaning:"电影",pos:"noun",example_en:"What's your favourite film?",example_zh:"你最喜欢的电影是什么？",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_082",word:"gallery",phonetic_uk:"/ˈɡæl.ər.i/",phonetic_us:"/ˈɡæl.ɚ.i/",meaning:"画廊；美术馆",pos:"noun",example_en:"We visited the art gallery on Sunday.",example_zh:"我们周日参观了美术馆。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_083",word:"instrument",phonetic_uk:"/ˈɪn.strə.mənt/",phonetic_us:"/ˈɪn.strə.mənt/",meaning:"乐器；工具",pos:"noun",example_en:"She can play three musical instruments.",example_zh:"她会演奏三种乐器。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_084",word:"magazine",phonetic_uk:"/ˌmæɡ.əˈziːn/",phonetic_us:"/ˈmæɡ.ə.ziːn/",meaning:"杂志",pos:"noun",example_en:"I buy a science magazine every month.",example_zh:"我每个月买一本科学杂志。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_085",word:"movie",phonetic_uk:"/ˈmuː.vi/",phonetic_us:"/ˈmuː.vi/",meaning:"电影",pos:"noun",example_en:"Let's go to the movies this weekend.",example_zh:"这个周末我们去看电影吧。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_086",word:"museum",phonetic_uk:"/mjuːˈziː.əm/",phonetic_us:"/mjuːˈziː.əm/",meaning:"博物馆",pos:"noun",example_en:"The science museum is very interesting.",example_zh:"科学博物馆非常有趣。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_087",word:"news",phonetic_uk:"/njuːz/",phonetic_us:"/nuːz/",meaning:"新闻",pos:"noun",example_en:"I watch the news every evening.",example_zh:"我每天晚上看新闻。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_088",word:"novel",phonetic_uk:"/ˈnɒv.əl/",phonetic_us:"/ˈnɑː.vəl/",meaning:"小说",pos:"noun",example_en:"I'm reading an exciting novel at the moment.",example_zh:"我目前正在读一本精彩的小说。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_089",word:"photograph",phonetic_uk:"/ˈfəʊ.tə.ɡrɑːf/",phonetic_us:"/ˈfoʊ.t̬oʊ.ɡræf/",meaning:"照片",pos:"noun",example_en:"I took a photograph of the sunset.",example_zh:"我拍了一张日落的照片。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_090",word:"podcast",phonetic_uk:"/ˈpɒd.kɑːst/",phonetic_us:"/ˈpɑːd.kæst/",meaning:"播客",pos:"noun",example_en:"I listen to a podcast on my way to school.",example_zh:"我在上学的路上听播客。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_091",word:"poem",phonetic_uk:"/ˈpəʊ.ɪm/",phonetic_us:"/ˈpoʊ.əm/",meaning:"诗",pos:"noun",example_en:"She wrote a poem about nature.",example_zh:"她写了一首关于自然的诗。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_092",word:"programme",phonetic_uk:"/ˈprəʊ.ɡræm/",phonetic_us:"/ˈproʊ.ɡræm/",meaning:"节目；计划",pos:"noun",example_en:"What's your favourite TV programme?",example_zh:"你最喜欢的电视节目是什么？",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_093",word:"radio",phonetic_uk:"/ˈreɪ.di.əʊ/",phonetic_us:"/ˈreɪ.di.oʊ/",meaning:"收音机；广播",pos:"noun",example_en:"I listen to the radio in the car.",example_zh:"我在车里听广播。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_094",word:"series",phonetic_uk:"/ˈsɪə.riːz/",phonetic_us:"/ˈsɪr.iːz/",meaning:"系列；连续剧",pos:"noun",example_en:"I'm watching a new series about detectives.",example_zh:"我在看一部新的侦探连续剧。",topic:"娱乐与媒体",level:"L1"},
  {id:"pet_095",word:"video",phonetic_uk:"/ˈvɪd.i.əʊ/",phonetic_us:"/ˈvɪd.i.oʊ/",meaning:"视频",pos:"noun",example_en:"We made a video for the school project.",example_zh:"我们为学校项目做了一个视频。",topic:"娱乐与媒体",level:"L1"},

  // ================================================================
  // 5. FOOD & DRINK (食物与饮料) - ~25 words
  // ================================================================
  {id:"pet_096",word:"barbecue",phonetic_uk:"/ˈbɑː.bɪ.kjuː/",phonetic_us:"/ˈbɑːr.bə.kjuː/",meaning:"烧烤",pos:"noun",example_en:"We had a barbecue in the garden.",example_zh:"我们在花园里搞了次烧烤。",topic:"食物与饮料",level:"L1"},
  {id:"pet_097",word:"bitter",phonetic_uk:"/ˈbɪt.ər/",phonetic_us:"/ˈbɪt̬.ɚ/",meaning:"苦的",pos:"adj",example_en:"The coffee was too bitter for me.",example_zh:"咖啡对我来说太苦了。",topic:"食物与饮料",level:"L1"},
  {id:"pet_098",word:"boil",phonetic_uk:"/bɔɪl/",phonetic_us:"/bɔɪl/",meaning:"煮沸；煮",pos:"verb",example_en:"Boil the water before adding the pasta.",example_zh:"先烧开水再加意面。",topic:"食物与饮料",level:"L1"},
  {id:"pet_099",word:"broccoli",phonetic_uk:"/ˈbrɒk.əl.i/",phonetic_us:"/ˈbrɑː.kəl.i/",meaning:"西兰花",pos:"noun",example_en:"Broccoli is a healthy vegetable.",example_zh:"西兰花是一种健康的蔬菜。",topic:"食物与饮料",level:"L1"},
  {id:"pet_100",word:"burger",phonetic_uk:"/ˈbɜː.ɡər/",phonetic_us:"/ˈbɝː.ɡɚ/",meaning:"汉堡包",pos:"noun",example_en:"I'd like a burger and fries, please.",example_zh:"我想要一个汉堡和薯条。",topic:"食物与饮料",level:"L1"},
  {id:"pet_101",word:"butter",phonetic_uk:"/ˈbʌt.ər/",phonetic_us:"/ˈbʌt̬.ɚ/",meaning:"黄油",pos:"noun",example_en:"Spread some butter on the bread.",example_zh:"在面包上抹些黄油。",topic:"食物与饮料",level:"L1"},
  {id:"pet_102",word:"cabbage",phonetic_uk:"/ˈkæb.ɪdʒ/",phonetic_us:"/ˈkæb.ɪdʒ/",meaning:"卷心菜",pos:"noun",example_en:"We had cabbage with our dinner.",example_zh:"我们晚饭吃了卷心菜。",topic:"食物与饮料",level:"L1"},
  {id:"pet_103",word:"café",phonetic_uk:"/ˈkæf.eɪ/",phonetic_us:"/kæfˈeɪ/",meaning:"咖啡馆；小餐馆",pos:"noun",example_en:"Let's meet at the café after school.",example_zh:"放学后我们在咖啡馆见面吧。",topic:"食物与饮料",level:"L1"},
  {id:"pet_104",word:"cereal",phonetic_uk:"/ˈsɪə.ri.əl/",phonetic_us:"/ˈsɪr.i.əl/",meaning:"麦片；谷物",pos:"noun",example_en:"I have cereal with milk for breakfast.",example_zh:"我早餐吃麦片加牛奶。",topic:"食物与饮料",level:"L1"},
  {id:"pet_105",word:"cheese",phonetic_uk:"/tʃiːz/",phonetic_us:"/tʃiːz/",meaning:"奶酪",pos:"noun",example_en:"I love pizza with lots of cheese.",example_zh:"我喜欢很多奶酪的披萨。",topic:"食物与饮料",level:"L1"},
  {id:"pet_106",word:"chef",phonetic_uk:"/ʃef/",phonetic_us:"/ʃef/",meaning:"厨师",pos:"noun",example_en:"My uncle works as a chef in a restaurant.",example_zh:"我叔叔在一家餐厅当厨师。",topic:"食物与饮料",level:"L1"},
  {id:"pet_107",word:"cherry",phonetic_uk:"/ˈtʃer.i/",phonetic_us:"/ˈtʃer.i/",meaning:"樱桃",pos:"noun",example_en:"Cherries are my favourite fruit in summer.",example_zh:"樱桃是我夏天最喜欢的水果。",topic:"食物与饮料",level:"L1"},
  {id:"pet_108",word:"chilli",phonetic_uk:"/ˈtʃɪl.i/",phonetic_us:"/ˈtʃɪl.i/",meaning:"辣椒",pos:"noun",example_en:"I don't like food with too much chilli.",example_zh:"我不喜欢太辣的食物。",topic:"食物与饮料",level:"L1"},
  {id:"pet_109",word:"coconut",phonetic_uk:"/ˈkəʊ.kə.nʌt/",phonetic_us:"/ˈkoʊ.kə.nʌt/",meaning:"椰子",pos:"noun",example_en:"I love the taste of coconut ice cream.",example_zh:"我喜欢椰子冰淇淋的味道。",topic:"食物与饮料",level:"L1"},
  {id:"pet_110",word:"cooker",phonetic_uk:"/ˈkʊk.ər/",phonetic_us:"/ˈkʊk.ɚ/",meaning:"炉灶；炊具",pos:"noun",example_en:"We bought a new electric cooker.",example_zh:"我们买了一个新的电炉灶。",topic:"食物与饮料",level:"L1"},
  {id:"pet_111",word:"cream",phonetic_uk:"/kriːm/",phonetic_us:"/kriːm/",meaning:"奶油；乳霜",pos:"noun",example_en:"I'd like strawberries with cream.",example_zh:"我想要草莓配奶油。",topic:"食物与饮料",level:"L1"},
  {id:"pet_112",word:"cucumber",phonetic_uk:"/ˈkjuː.kʌm.bər/",phonetic_us:"/ˈkjuː.kʌm.bɚ/",meaning:"黄瓜",pos:"noun",example_en:"Add some cucumber to the salad.",example_zh:"在沙拉里加些黄瓜。",topic:"食物与饮料",level:"L1"},
  {id:"pet_113",word:"curry",phonetic_uk:"/ˈkʌr.i/",phonetic_us:"/ˈkɝː.i/",meaning:"咖喱",pos:"noun",example_en:"We had chicken curry for dinner.",example_zh:"我们晚饭吃了咖喱鸡。",topic:"食物与饮料",level:"L1"},
  {id:"pet_114",word:"delicious",phonetic_uk:"/dɪˈlɪʃ.əs/",phonetic_us:"/dɪˈlɪʃ.əs/",meaning:"美味的",pos:"adj",example_en:"The cake was absolutely delicious.",example_zh:"这个蛋糕简直太美味了。",topic:"食物与饮料",level:"L1"},
  {id:"pet_115",word:"dessert",phonetic_uk:"/dɪˈzɜːt/",phonetic_us:"/dɪˈzɝːt/",meaning:"甜点",pos:"noun",example_en:"What would you like for dessert?",example_zh:"你想吃什么甜点？",topic:"食物与饮料",level:"L1"},
  {id:"pet_116",word:"flavour",phonetic_uk:"/ˈfleɪ.vər/",phonetic_us:"/ˈfleɪ.vɚ/",meaning:"味道；风味",pos:"noun",example_en:"Which flavour of ice cream do you want?",example_zh:"你想要什么口味的冰淇淋？",topic:"食物与饮料",level:"L1"},
  {id:"pet_117",word:"grape",phonetic_uk:"/ɡreɪp/",phonetic_us:"/ɡreɪp/",meaning:"葡萄",pos:"noun",example_en:"I bought a bunch of grapes from the market.",example_zh:"我从市场买了一串葡萄。",topic:"食物与饮料",level:"L1"},
  {id:"pet_118",word:"lemon",phonetic_uk:"/ˈlem.ən/",phonetic_us:"/ˈlem.ən/",meaning:"柠檬",pos:"noun",example_en:"I like lemon juice in my tea.",example_zh:"我喜欢在茶里加柠檬汁。",topic:"食物与饮料",level:"L1"},
  {id:"pet_119",word:"mushroom",phonetic_uk:"/ˈmʌʃ.ruːm/",phonetic_us:"/ˈmʌʃ.ruːm/",meaning:"蘑菇",pos:"noun",example_en:"We picked mushrooms in the forest.",example_zh:"我们在森林里采了蘑菇。",topic:"食物与饮料",level:"L1"},
  {id:"pet_120",word:"recipe",phonetic_uk:"/ˈres.ɪ.pi/",phonetic_us:"/ˈres.ə.pi/",meaning:"食谱；烹饪法",pos:"noun",example_en:"My mother gave me her secret recipe.",example_zh:"妈妈把她的秘方给了我。",topic:"食物与饮料",level:"L1"},

  // ================================================================
  // 6. HEALTH & SPORTS (健康与运动) - ~25 words
  // ================================================================
  {id:"pet_121",word:"active",phonetic_uk:"/ˈæk.tɪv/",phonetic_us:"/ˈæk.tɪv/",meaning:"活跃的；积极的",pos:"adj",example_en:"You should stay active and exercise regularly.",example_zh:"你应该保持活跃，定期锻炼。",topic:"健康与运动",level:"L1"},
  {id:"pet_122",word:"athlete",phonetic_uk:"/ˈæθ.liːt/",phonetic_us:"/ˈæθ.liːt/",meaning:"运动员",pos:"noun",example_en:"She trained hard to become an athlete.",example_zh:"她刻苦训练成为一名运动员。",topic:"健康与运动",level:"L1"},
  {id:"pet_123",word:"athletics",phonetic_uk:"/æθˈlet.ɪks/",phonetic_us:"/æθˈlet̬.ɪks/",meaning:"田径运动",pos:"noun",example_en:"Athletics is my favourite sport at school.",example_zh:"田径是我在学校最喜欢的运动。",topic:"健康与运动",level:"L1"},
  {id:"pet_124",word:"bleed",phonetic_uk:"/bliːd/",phonetic_us:"/bliːd/",meaning:"流血",pos:"verb",example_en:"His nose started to bleed after the fall.",example_zh:"摔倒后他的鼻子开始流血。",topic:"健康与运动",level:"L1"},
  {id:"pet_125",word:"breath",phonetic_uk:"/breθ/",phonetic_us:"/breθ/",meaning:"呼吸；气息",pos:"noun",example_en:"Take a deep breath and relax.",example_zh:"深呼吸，放松。",topic:"健康与运动",level:"L1"},
  {id:"pet_126",word:"breathe",phonetic_uk:"/briːð/",phonetic_us:"/briːð/",meaning:"呼吸",pos:"verb",example_en:"It's hard to breathe at high altitudes.",example_zh:"在高海拔地区呼吸很困难。",topic:"健康与运动",level:"L1"},
  {id:"pet_127",word:"champion",phonetic_uk:"/ˈtʃæm.pi.ən/",phonetic_us:"/ˈtʃæm.pi.ən/",meaning:"冠军",pos:"noun",example_en:"She became the national champion.",example_zh:"她成为了全国冠军。",topic:"健康与运动",level:"L1"},
  {id:"pet_128",word:"clinic",phonetic_uk:"/ˈklɪn.ɪk/",phonetic_us:"/ˈklɪn.ɪk/",meaning:"诊所",pos:"noun",example_en:"I went to the dental clinic for a check-up.",example_zh:"我去牙科诊所做了检查。",topic:"健康与运动",level:"L1"},
  {id:"pet_129",word:"competition",phonetic_uk:"/ˌkɒm.pəˈtɪʃ.ən/",phonetic_us:"/ˌkɑːm.pəˈtɪʃ.ən/",meaning:"比赛；竞赛",pos:"noun",example_en:"I entered a swimming competition.",example_zh:"我参加了一个游泳比赛。",topic:"健康与运动",level:"L1"},
  {id:"pet_130",word:"cure",phonetic_uk:"/kjʊər/",phonetic_us:"/kjʊr/",meaning:"治愈；治疗",pos:"verb",example_en:"Doctors are working to cure the disease.",example_zh:"医生们正在努力治愈这种疾病。",topic:"健康与运动",level:"L1"},
  {id:"pet_131",word:"diet",phonetic_uk:"/ˈdaɪ.ət/",phonetic_us:"/ˈdaɪ.ət/",meaning:"饮食；节食",pos:"noun",example_en:"A healthy diet includes lots of vegetables.",example_zh:"健康的饮食包括大量蔬菜。",topic:"健康与运动",level:"L1"},
  {id:"pet_132",word:"exercise",phonetic_uk:"/ˈek.sə.saɪz/",phonetic_us:"/ˈek.sɚ.saɪz/",meaning:"锻炼；练习",pos:"noun",example_en:"I do exercise every morning before school.",example_zh:"我每天早上上学前锻炼。",topic:"健康与运动",level:"L1"},
  {id:"pet_133",word:"fitness",phonetic_uk:"/ˈfɪt.nəs/",phonetic_us:"/ˈfɪt.nəs/",meaning:"健康；体能",pos:"noun",example_en:"She goes to the fitness centre twice a week.",example_zh:"她每周去两次健身中心。",topic:"健康与运动",level:"L1"},
  {id:"pet_134",word:"headache",phonetic_uk:"/ˈhed.eɪk/",phonetic_us:"/ˈhed.eɪk/",meaning:"头痛",pos:"noun",example_en:"I have a headache and need to rest.",example_zh:"我头痛，需要休息一下。",topic:"健康与运动",level:"L1"},
  {id:"pet_135",word:"health",phonetic_uk:"/helθ/",phonetic_us:"/helθ/",meaning:"健康",pos:"noun",example_en:"Smoking is bad for your health.",example_zh:"吸烟有害健康。",topic:"健康与运动",level:"L1"},
  {id:"pet_136",word:"injury",phonetic_uk:"/ˈɪn.dʒər.i/",phonetic_us:"/ˈɪn.dʒɚ.i/",meaning:"受伤；伤害",pos:"noun",example_en:"He cannot play because of a knee injury.",example_zh:"他因为膝盖受伤不能上场。",topic:"健康与运动",level:"L1"},
  {id:"pet_137",word:"match",phonetic_uk:"/mætʃ/",phonetic_us:"/mætʃ/",meaning:"比赛",pos:"noun",example_en:"We won the football match 3-1.",example_zh:"我们以3:1赢了足球比赛。",topic:"健康与运动",level:"L1"},
  {id:"pet_138",word:"medicine",phonetic_uk:"/ˈmed.ɪ.sən/",phonetic_us:"/ˈmed.ɪ.sən/",meaning:"药；医学",pos:"noun",example_en:"The doctor gave me some medicine for my cough.",example_zh:"医生给我开了些咳嗽药。",topic:"健康与运动",level:"L1"},
  {id:"pet_139",word:"muscle",phonetic_uk:"/ˈmʌs.əl/",phonetic_us:"/ˈmʌs.əl/",meaning:"肌肉",pos:"noun",example_en:"Running helps build strong leg muscles.",example_zh:"跑步有助于练出强壮的大腿肌肉。",topic:"健康与运动",level:"L1"},
  {id:"pet_140",word:"patient",phonetic_uk:"/ˈpeɪ.ʃənt/",phonetic_us:"/ˈpeɪ.ʃənt/",meaning:"病人；耐心的",pos:"noun",example_en:"The nurse took care of the patient.",example_zh:"护士照顾了那位病人。",topic:"健康与运动",level:"L1"},
  {id:"pet_141",word:"practice",phonetic_uk:"/ˈpræk.tɪs/",phonetic_us:"/ˈpræk.tɪs/",meaning:"练习；实践",pos:"noun",example_en:"It takes a lot of practice to play the piano well.",example_zh:"弹好钢琴需要大量练习。",topic:"健康与运动",level:"L1"},
  {id:"pet_142",word:"race",phonetic_uk:"/reɪs/",phonetic_us:"/reɪs/",meaning:"比赛；竞赛",pos:"noun",example_en:"She won the 100-metre race.",example_zh:"她赢得了100米赛跑。",topic:"健康与运动",level:"L1"},
  {id:"pet_143",word:"team",phonetic_uk:"/tiːm/",phonetic_us:"/tiːm/",meaning:"团队；队伍",pos:"noun",example_en:"Our team won the basketball game.",example_zh:"我们队赢了篮球比赛。",topic:"健康与运动",level:"L1"},
  {id:"pet_144",word:"train",phonetic_uk:"/treɪn/",phonetic_us:"/treɪn/",meaning:"训练；培训",pos:"verb",example_en:"The players train every day after school.",example_zh:"队员们每天放学后训练。",topic:"健康与运动",level:"L1"},
  {id:"pet_145",word:"walking",phonetic_uk:"/ˈwɔː.kɪŋ/",phonetic_us:"/ˈwɑː.kɪŋ/",meaning:"步行；散步",pos:"noun",example_en:"Walking is good exercise for everyone.",example_zh:"散步对每个人来说都是好运动。",topic:"健康与运动",level:"L1"},

  // ================================================================
  // 7. TRAVEL & TRANSPORT (旅行与交通) - ~25 words
  // ================================================================
  {id:"pet_146",word:"abroad",phonetic_uk:"/əˈbrɔːd/",phonetic_us:"/əˈbrɑːd/",meaning:"在国外；到国外",pos:"adv",example_en:"I want to study abroad in the future.",example_zh:"我将来想出国留学。",topic:"旅行与交通",level:"L1"},
  {id:"pet_147",word:"airline",phonetic_uk:"/ˈeə.laɪn/",phonetic_us:"/ˈer.laɪn/",meaning:"航空公司",pos:"noun",example_en:"Which airline are you flying with?",example_zh:"你乘坐哪家航空公司的航班？",topic:"旅行与交通",level:"L1"},
  {id:"pet_148",word:"airport",phonetic_uk:"/ˈeə.pɔːt/",phonetic_us:"/ˈer.pɔːrt/",meaning:"机场",pos:"noun",example_en:"We arrived at the airport two hours early.",example_zh:"我们提前两小时到达了机场。",topic:"旅行与交通",level:"L1"},
  {id:"pet_149",word:"boarding pass",phonetic_uk:"/ˈbɔː.dɪŋ pɑːs/",phonetic_us:"/ˈbɔːr.dɪŋ pæs/",meaning:"登机牌",pos:"noun",example_en:"Please show your boarding pass at the gate.",example_zh:"请在登机口出示您的登机牌。",topic:"旅行与交通",level:"L1"},
  {id:"pet_150",word:"coach",phonetic_uk:"/kəʊtʃ/",phonetic_us:"/koʊtʃ/",meaning:"长途汽车；教练",pos:"noun",example_en:"We took a coach to London.",example_zh:"我们坐长途汽车去了伦敦。",topic:"旅行与交通",level:"L1"},
  {id:"pet_151",word:"coast",phonetic_uk:"/kəʊst/",phonetic_us:"/koʊst/",meaning:"海岸",pos:"noun",example_en:"They live in a small town on the coast.",example_zh:"他们住在海岸边的一个小镇上。",topic:"旅行与交通",level:"L1"},
  {id:"pet_152",word:"cruise",phonetic_uk:"/kruːz/",phonetic_us:"/kruːz/",meaning:"邮轮旅行",pos:"noun",example_en:"They went on a cruise around the islands.",example_zh:"他们乘邮轮环游了那些岛屿。",topic:"旅行与交通",level:"L1"},
  {id:"pet_153",word:"customs",phonetic_uk:"/ˈkʌs.təmz/",phonetic_us:"/ˈkʌs.təmz/",meaning:"海关",pos:"noun",example_en:"We had to go through customs at the airport.",example_zh:"我们必须在机场过海关。",topic:"旅行与交通",level:"L1"},
  {id:"pet_154",word:"destination",phonetic_uk:"/ˌdes.tɪˈneɪ.ʃən/",phonetic_us:"/ˌdes.təˈneɪ.ʃən/",meaning:"目的地",pos:"noun",example_en:"Our destination is the capital city.",example_zh:"我们的目的地是首都。",topic:"旅行与交通",level:"L1"},
  {id:"pet_155",word:"driver",phonetic_uk:"/ˈdraɪ.vər/",phonetic_us:"/ˈdraɪ.vɚ/",meaning:"司机；驾驶员",pos:"noun",example_en:"The bus driver was very friendly.",example_zh:"公共汽车司机非常友善。",topic:"旅行与交通",level:"L1"},
  {id:"pet_156",word:"flight",phonetic_uk:"/flaɪt/",phonetic_us:"/flaɪt/",meaning:"航班；飞行",pos:"noun",example_en:"Our flight was delayed by two hours.",example_zh:"我们的航班延误了两个小时。",topic:"旅行与交通",level:"L1"},
  {id:"pet_157",word:"garage",phonetic_uk:"/ˈɡær.ɑːʒ/",phonetic_us:"/ɡəˈrɑːʒ/",meaning:"车库；修车厂",pos:"noun",example_en:"We keep our car in the garage.",example_zh:"我们把车停在车库里。",topic:"旅行与交通",level:"L1"},
  {id:"pet_158",word:"guide",phonetic_uk:"/ɡaɪd/",phonetic_us:"/ɡaɪd/",meaning:"导游；指南",pos:"noun",example_en:"Our guide showed us around the city.",example_zh:"导游带我们参观了城市。",topic:"旅行与交通",level:"L1"},
  {id:"pet_159",word:"luggage",phonetic_uk:"/ˈlʌɡ.ɪdʒ/",phonetic_us:"/ˈlʌɡ.ɪdʒ/",meaning:"行李",pos:"noun",example_en:"I need to pack my luggage tonight.",example_zh:"我今晚需要收拾行李。",topic:"旅行与交通",level:"L1"},
  {id:"pet_160",word:"map",phonetic_uk:"/mæp/",phonetic_us:"/mæp/",meaning:"地图",pos:"noun",example_en:"Can you show me on the map where we are?",example_zh:"你能在地图上给我看看我们在哪吗？",topic:"旅行与交通",level:"L1"},
  {id:"pet_161",word:"passenger",phonetic_uk:"/ˈpæs.ən.dʒər/",phonetic_us:"/ˈpæs.ən.dʒɚ/",meaning:"乘客",pos:"noun",example_en:"All passengers must wear a seat belt.",example_zh:"所有乘客必须系安全带。",topic:"旅行与交通",level:"L1"},
  {id:"pet_162",word:"passport",phonetic_uk:"/ˈpɑːs.pɔːt/",phonetic_us:"/ˈpæs.pɔːrt/",meaning:"护照",pos:"noun",example_en:"Don't forget to bring your passport.",example_zh:"别忘了带护照。",topic:"旅行与交通",level:"L1"},
  {id:"pet_163",word:"petrol",phonetic_uk:"/ˈpet.rəl/",phonetic_us:"/ˈpet.rəl/",meaning:"汽油",pos:"noun",example_en:"We need to stop for petrol.",example_zh:"我们需要停下来加油。",topic:"旅行与交通",level:"L1"},
  {id:"pet_164",word:"platform",phonetic_uk:"/ˈplæt.fɔːm/",phonetic_us:"/ˈplæt.fɔːrm/",meaning:"站台",pos:"noun",example_en:"The train leaves from platform 3.",example_zh:"火车从3号站台出发。",topic:"旅行与交通",level:"L1"},
  {id:"pet_165",word:"reserve",phonetic_uk:"/rɪˈzɜːv/",phonetic_us:"/rɪˈzɝːv/",meaning:"预订；保留",pos:"verb",example_en:"I'd like to reserve a table for four.",example_zh:"我想预订一张四人桌。",topic:"旅行与交通",level:"L1"},
  {id:"pet_166",word:"route",phonetic_uk:"/ruːt/",phonetic_us:"/ruːt/",meaning:"路线",pos:"noun",example_en:"What's the quickest route to the station?",example_zh:"去车站最快的路线是什么？",topic:"旅行与交通",level:"L1"},
  {id:"pet_167",word:"suitcase",phonetic_uk:"/ˈsuːt.keɪs/",phonetic_us:"/ˈsuːt.keɪs/",meaning:"手提箱",pos:"noun",example_en:"I packed my clothes in a suitcase.",example_zh:"我把衣服装进了手提箱。",topic:"旅行与交通",level:"L1"},
  {id:"pet_168",word:"traffic",phonetic_uk:"/ˈtræf.ɪk/",phonetic_us:"/ˈtræf.ɪk/",meaning:"交通；车流",pos:"noun",example_en:"I was late because of the traffic.",example_zh:"我因为堵车迟到了。",topic:"旅行与交通",level:"L1"},
  {id:"pet_169",word:"vehicle",phonetic_uk:"/ˈviː.ɪ.kəl/",phonetic_us:"/ˈviː.ə.kəl/",meaning:"车辆",pos:"noun",example_en:"There are too many vehicles on the road.",example_zh:"路上的车辆太多了。",topic:"旅行与交通",level:"L1"},
  {id:"pet_170",word:"visitor",phonetic_uk:"/ˈvɪz.ɪ.tər/",phonetic_us:"/ˈvɪz.ɪ.t̬ɚ/",meaning:"游客；访客",pos:"noun",example_en:"The museum has thousands of visitors each year.",example_zh:"这个博物馆每年有成千上万的游客。",topic:"旅行与交通",level:"L1"},

  // ================================================================
  // 8. FEELINGS & PERSONALITY (情感与性格) - ~25 words
  // ================================================================
  {id:"pet_171",word:"afraid",phonetic_uk:"/əˈfreɪd/",phonetic_us:"/əˈfreɪd/",meaning:"害怕的",pos:"adj",example_en:"She is afraid of spiders.",example_zh:"她害怕蜘蛛。",topic:"情感与性格",level:"L1"},
  {id:"pet_172",word:"amazing",phonetic_uk:"/əˈmeɪ.zɪŋ/",phonetic_us:"/əˈmeɪ.zɪŋ/",meaning:"惊人的；了不起的",pos:"adj",example_en:"The view from the top was amazing.",example_zh:"山顶的景色令人惊叹。",topic:"情感与性格",level:"L1"},
  {id:"pet_173",word:"ambitious",phonetic_uk:"/æmˈbɪʃ.əs/",phonetic_us:"/æmˈbɪʃ.əs/",meaning:"有雄心的",pos:"adj",example_en:"She is ambitious and wants to be a doctor.",example_zh:"她很有雄心，想成为一名医生。",topic:"情感与性格",level:"L1"},
  {id:"pet_174",word:"angry",phonetic_uk:"/ˈæŋ.ɡri/",phonetic_us:"/ˈæŋ.ɡri/",meaning:"生气的",pos:"adj",example_en:"My dad was angry because I broke the window.",example_zh:"我爸爸很生气，因为我打碎了窗户。",topic:"情感与性格",level:"L1"},
  {id:"pet_175",word:"anxious",phonetic_uk:"/ˈæŋk.ʃəs/",phonetic_us:"/ˈæŋk.ʃəs/",meaning:"焦虑的",pos:"adj",example_en:"I feel anxious before exams.",example_zh:"考试前我感到焦虑。",topic:"情感与性格",level:"L1"},
  {id:"pet_176",word:"ashamed",phonetic_uk:"/əˈʃeɪmd/",phonetic_us:"/əˈʃeɪmd/",meaning:"羞愧的",pos:"adj",example_en:"He felt ashamed for telling a lie.",example_zh:"他因为撒谎而感到羞愧。",topic:"情感与性格",level:"L1"},
  {id:"pet_177",word:"brave",phonetic_uk:"/breɪv/",phonetic_us:"/breɪv/",meaning:"勇敢的",pos:"adj",example_en:"The firefighters were very brave.",example_zh:"消防员们非常勇敢。",topic:"情感与性格",level:"L1"},
  {id:"pet_178",word:"calm",phonetic_uk:"/kɑːm/",phonetic_us:"/kɑːm/",meaning:"冷静的；平静的",pos:"adj",example_en:"Try to stay calm during the test.",example_zh:"考试时尽量保持冷静。",topic:"情感与性格",level:"L1"},
  {id:"pet_179",word:"confident",phonetic_uk:"/ˈkɒn.fɪ.dənt/",phonetic_us:"/ˈkɑːn.fə.dənt/",meaning:"自信的",pos:"adj",example_en:"She is confident she will pass the exam.",example_zh:"她自信能通过考试。",topic:"情感与性格",level:"L1"},
  {id:"pet_180",word:"confused",phonetic_uk:"/kənˈfjuːzd/",phonetic_us:"/kənˈfjuːzd/",meaning:"困惑的",pos:"adj",example_en:"I'm confused about the homework instructions.",example_zh:"我对作业要求感到困惑。",topic:"情感与性格",level:"L1"},
  {id:"pet_181",word:"crazy",phonetic_uk:"/ˈkreɪ.zi/",phonetic_us:"/ˈkreɪ.zi/",meaning:"疯狂的",pos:"adj",example_en:"You're crazy to go out in this storm!",example_zh:"你疯了吧，这么大的暴风雨还出去！",topic:"情感与性格",level:"L1"},
  {id:"pet_182",word:"curious",phonetic_uk:"/ˈkjʊə.ri.əs/",phonetic_us:"/ˈkjʊr.i.əs/",meaning:"好奇的",pos:"adj",example_en:"Children are naturally curious about the world.",example_zh:"孩子天生对世界充满好奇。",topic:"情感与性格",level:"L1"},
  {id:"pet_183",word:"disappointed",phonetic_uk:"/ˌdɪs.əˈpɔɪn.tɪd/",phonetic_us:"/ˌdɪs.əˈpɔɪn.t̬ɪd/",meaning:"失望的",pos:"adj",example_en:"I was disappointed that I didn't win.",example_zh:"我很失望没有赢。",topic:"情感与性格",level:"L1"},
  {id:"pet_184",word:"embarrassed",phonetic_uk:"/ɪmˈbær.əst/",phonetic_us:"/ɪmˈber.əst/",meaning:"尴尬的",pos:"adj",example_en:"I felt embarrassed when I fell over.",example_zh:"我摔倒时感到很尴尬。",topic:"情感与性格",level:"L1"},
  {id:"pet_185",word:"excited",phonetic_uk:"/ɪkˈsaɪ.tɪd/",phonetic_us:"/ɪkˈsaɪ.t̬ɪd/",meaning:"兴奋的",pos:"adj",example_en:"The children are excited about the trip.",example_zh:"孩子们对这次旅行很兴奋。",topic:"情感与性格",level:"L1"},
  {id:"pet_186",word:"frightened",phonetic_uk:"/ˈfraɪ.tənd/",phonetic_us:"/ˈfraɪ.tənd/",meaning:"受惊吓的",pos:"adj",example_en:"The loud noise frightened the baby.",example_zh:"巨大的响声吓到了婴儿。",topic:"情感与性格",level:"L1"},
  {id:"pet_187",word:"generous",phonetic_uk:"/ˈdʒen.ər.əs/",phonetic_us:"/ˈdʒen.ər.əs/",meaning:"慷慨的",pos:"adj",example_en:"He is very generous and often gives gifts.",example_zh:"他非常慷慨，经常送礼物。",topic:"情感与性格",level:"L1"},
  {id:"pet_188",word:"grateful",phonetic_uk:"/ˈɡreɪt.fəl/",phonetic_us:"/ˈɡreɪt.fəl/",meaning:"感激的",pos:"adj",example_en:"I'm grateful for all your help.",example_zh:"我感激你所有的帮助。",topic:"情感与性格",level:"L1"},
  {id:"pet_189",word:"honest",phonetic_uk:"/ˈɒn.ɪst/",phonetic_us:"/ˈɑː.nɪst/",meaning:"诚实的",pos:"adj",example_en:"Please be honest and tell me the truth.",example_zh:"请诚实一点，告诉我真相。",topic:"情感与性格",level:"L1"},
  {id:"pet_190",word:"jealous",phonetic_uk:"/ˈdʒel.əs/",phonetic_us:"/ˈdʒel.əs/",meaning:"嫉妒的",pos:"adj",example_en:"She felt jealous of her sister's success.",example_zh:"她嫉妒妹妹的成功。",topic:"情感与性格",level:"L1"},
  {id:"pet_191",word:"lonely",phonetic_uk:"/ˈləʊn.li/",phonetic_us:"/ˈloʊn.li/",meaning:"孤独的",pos:"adj",example_en:"He felt lonely after his friends moved away.",example_zh:"朋友搬走后他感到很孤独。",topic:"情感与性格",level:"L1"},
  {id:"pet_192",word:"nervous",phonetic_uk:"/ˈnɜː.vəs/",phonetic_us:"/ˈnɝː.vəs/",meaning:"紧张的",pos:"adj",example_en:"I always get nervous before a speech.",example_zh:"我演讲前总是很紧张。",topic:"情感与性格",level:"L1"},
  {id:"pet_193",word:"polite",phonetic_uk:"/pəˈlaɪt/",phonetic_us:"/pəˈlaɪt/",meaning:"礼貌的",pos:"adj",example_en:"It's polite to say 'thank you'.",example_zh:"说'谢谢'是礼貌的。",topic:"情感与性格",level:"L1"},
  {id:"pet_194",word:"proud",phonetic_uk:"/praʊd/",phonetic_us:"/praʊd/",meaning:"自豪的；骄傲的",pos:"adj",example_en:"My parents are proud of my grades.",example_zh:"父母为我的成绩感到骄傲。",topic:"情感与性格",level:"L1"},
  {id:"pet_195",word:"serious",phonetic_uk:"/ˈsɪə.ri.əs/",phonetic_us:"/ˈsɪr.i.əs/",meaning:"严肃的；严重的",pos:"adj",example_en:"The teacher had a serious expression.",example_zh:"老师表情严肃。",topic:"情感与性格",level:"L1"},

  // ================================================================
  // 9. WORK & JOBS (职业与工作) - ~25 words
  // ================================================================
  {id:"pet_196",word:"accountant",phonetic_uk:"/əˈkaʊn.tənt/",phonetic_us:"/əˈkaʊn.t̬ənt/",meaning:"会计",pos:"noun",example_en:"My aunt works as an accountant.",example_zh:"我阿姨是做会计的。",topic:"职业与工作",level:"L1"},
  {id:"pet_197",word:"application",phonetic_uk:"/ˌæp.lɪˈkeɪ.ʃən/",phonetic_us:"/ˌæp.ləˈkeɪ.ʃən/",meaning:"申请；应用",pos:"noun",example_en:"I filled in a job application form.",example_zh:"我填写了一张工作申请表。",topic:"职业与工作",level:"L1"},
  {id:"pet_198",word:"apply",phonetic_uk:"/əˈplaɪ/",phonetic_us:"/əˈplaɪ/",meaning:"申请；应用",pos:"verb",example_en:"I want to apply for a part-time job.",example_zh:"我想申请一份兼职工作。",topic:"职业与工作",level:"L1"},
  {id:"pet_199",word:"architect",phonetic_uk:"/ˈɑː.kɪ.tekt/",phonetic_us:"/ˈɑːr.kə.tekt/",meaning:"建筑师",pos:"noun",example_en:"The architect designed a beautiful building.",example_zh:"建筑师设计了一栋漂亮的建筑。",topic:"职业与工作",level:"L1"},
  {id:"pet_200",word:"boss",phonetic_uk:"/bɒs/",phonetic_us:"/bɑːs/",meaning:"老板；上司",pos:"noun",example_en:"My boss gave me a new project to work on.",example_zh:"我老板给了我一个新项目。",topic:"职业与工作",level:"L1"},
  {id:"pet_201",word:"business",phonetic_uk:"/ˈbɪz.nɪs/",phonetic_us:"/ˈbɪz.nɪs/",meaning:"生意；商业",pos:"noun",example_en:"My father runs a small business.",example_zh:"我父亲经营一家小生意。",topic:"职业与工作",level:"L1"},
  {id:"pet_202",word:"career",phonetic_uk:"/kəˈrɪər/",phonetic_us:"/kəˈrɪr/",meaning:"职业；事业",pos:"noun",example_en:"She wants a career in medicine.",example_zh:"她想从事医学事业。",topic:"职业与工作",level:"L1"},
  {id:"pet_203",word:"colleague",phonetic_uk:"/ˈkɒl.iːɡ/",phonetic_us:"/ˈkɑː.liːɡ/",meaning:"同事",pos:"noun",example_en:"I get along well with my colleagues.",example_zh:"我和同事们相处得很好。",topic:"职业与工作",level:"L1"},
  {id:"pet_204",word:"company",phonetic_uk:"/ˈkʌm.pə.ni/",phonetic_us:"/ˈkʌm.pə.ni/",meaning:"公司",pos:"noun",example_en:"She works for a large technology company.",example_zh:"她在一家大型科技公司工作。",topic:"职业与工作",level:"L1"},
  {id:"pet_205",word:"customer",phonetic_uk:"/ˈkʌs.tə.mər/",phonetic_us:"/ˈkʌs.tə.mɚ/",meaning:"顾客",pos:"noun",example_en:"The shop assistant helped the customer.",example_zh:"店员帮助了那位顾客。",topic:"职业与工作",level:"L1"},
  {id:"pet_206",word:"earn",phonetic_uk:"/ɜːn/",phonetic_us:"/ɝːn/",meaning:"挣；赚",pos:"verb",example_en:"How much does he earn each month?",example_zh:"他每月挣多少钱？",topic:"职业与工作",level:"L1"},
  {id:"pet_207",word:"employ",phonetic_uk:"/ɪmˈplɔɪ/",phonetic_us:"/ɪmˈplɔɪ/",meaning:"雇用",pos:"verb",example_en:"The factory employs over 500 workers.",example_zh:"这家工厂雇用了500多名工人。",topic:"职业与工作",level:"L1"},
  {id:"pet_208",word:"experience",phonetic_uk:"/ɪkˈspɪə.ri.əns/",phonetic_us:"/ɪkˈspɪr.i.əns/",meaning:"经验；经历",pos:"noun",example_en:"Do you have any work experience?",example_zh:"你有工作经验吗？",topic:"职业与工作",level:"L1"},
  {id:"pet_209",word:"factory",phonetic_uk:"/ˈfæk.tər.i/",phonetic_us:"/ˈfæk.tɚ.i/",meaning:"工厂",pos:"noun",example_en:"The factory produces cars for export.",example_zh:"这家工厂生产出口汽车。",topic:"职业与工作",level:"L1"},
  {id:"pet_210",word:"interview",phonetic_uk:"/ˈɪn.tə.vjuː/",phonetic_us:"/ˈɪn.t̬ɚ.vjuː/",meaning:"面试；采访",pos:"noun",example_en:"I have a job interview tomorrow morning.",example_zh:"我明天上午有一个求职面试。",topic:"职业与工作",level:"L1"},
  {id:"pet_211",word:"manager",phonetic_uk:"/ˈmæn.ɪ.dʒər/",phonetic_us:"/ˈmæn.ə.dʒɚ/",meaning:"经理",pos:"noun",example_en:"She was promoted to sales manager.",example_zh:"她被提升为销售经理。",topic:"职业与工作",level:"L1"},
  {id:"pet_212",word:"meeting",phonetic_uk:"/ˈmiː.tɪŋ/",phonetic_us:"/ˈmiː.t̬ɪŋ/",meaning:"会议",pos:"noun",example_en:"I have a meeting at 10 o'clock.",example_zh:"我10点有个会议。",topic:"职业与工作",level:"L1"},
  {id:"pet_213",word:"office",phonetic_uk:"/ˈɒf.ɪs/",phonetic_us:"/ˈɑː.fɪs/",meaning:"办公室",pos:"noun",example_en:"I work in an office near the station.",example_zh:"我在车站附近的办公室工作。",topic:"职业与工作",level:"L1"},
  {id:"pet_214",word:"opportunity",phonetic_uk:"/ˌɒp.əˈtjuː.nə.ti/",phonetic_us:"/ˌɑː.pɚˈtuː.nə.t̬i/",meaning:"机会",pos:"noun",example_en:"This is a great opportunity to learn.",example_zh:"这是一个很好的学习机会。",topic:"职业与工作",level:"L1"},
  {id:"pet_215",word:"position",phonetic_uk:"/pəˈzɪʃ.ən/",phonetic_us:"/pəˈzɪʃ.ən/",meaning:"职位；位置",pos:"noun",example_en:"He applied for a position at the bank.",example_zh:"他申请了银行的一个职位。",topic:"职业与工作",level:"L1"},
  {id:"pet_216",word:"salary",phonetic_uk:"/ˈsæl.ər.i/",phonetic_us:"/ˈsæl.ɚ.i/",meaning:"工资；薪水",pos:"noun",example_en:"The job offers a good salary.",example_zh:"这份工作提供不错的薪水。",topic:"职业与工作",level:"L1"},
  {id:"pet_217",word:"staff",phonetic_uk:"/stɑːf/",phonetic_us:"/stæf/",meaning:"员工；工作人员",pos:"noun",example_en:"The hotel staff were very helpful.",example_zh:"酒店员工非常乐于助人。",topic:"职业与工作",level:"L1"},
  {id:"pet_218",word:"succeed",phonetic_uk:"/səkˈsiːd/",phonetic_us:"/səkˈsiːd/",meaning:"成功",pos:"verb",example_en:"If you work hard, you will succeed.",example_zh:"如果你努力，你就会成功。",topic:"职业与工作",level:"L1"},
  {id:"pet_219",word:"task",phonetic_uk:"/tɑːsk/",phonetic_us:"/tæsk/",meaning:"任务",pos:"noun",example_en:"My first task was to organise the files.",example_zh:"我的第一个任务是整理文件。",topic:"职业与工作",level:"L1"},
  {id:"pet_220",word:"volunteer",phonetic_uk:"/ˌvɒl.ənˈtɪər/",phonetic_us:"/ˌvɑː.lənˈtɪr/",meaning:"志愿者",pos:"noun",example_en:"She works as a volunteer at the animal shelter.",example_zh:"她在动物收容所做志愿者。",topic:"职业与工作",level:"L1"},

  // ================================================================
  // 10. NATURE & ENVIRONMENT (自然与环境) - ~20 words
  // ================================================================
  {id:"pet_221",word:"atmosphere",phonetic_uk:"/ˈæt.mə.sfɪər/",phonetic_us:"/ˈæt.mə.sfɪr/",meaning:"气氛；大气层",pos:"noun",example_en:"The restaurant has a friendly atmosphere.",example_zh:"这家餐厅气氛友好。",topic:"自然与环境",level:"L1"},
  {id:"pet_222",word:"climate",phonetic_uk:"/ˈklaɪ.mət/",phonetic_us:"/ˈklaɪ.mət/",meaning:"气候",pos:"noun",example_en:"The climate in this region is mild.",example_zh:"这个地区的气候温和。",topic:"自然与环境",level:"L1"},
  {id:"pet_223",word:"continent",phonetic_uk:"/ˈkɒn.tɪ.nənt/",phonetic_us:"/ˈkɑːn.t̬ən.ənt/",meaning:"洲；大陆",pos:"noun",example_en:"Africa is the second largest continent.",example_zh:"非洲是第二大的大陆。",topic:"自然与环境",level:"L1"},
  {id:"pet_224",word:"countryside",phonetic_uk:"/ˈkʌn.tri.saɪd/",phonetic_us:"/ˈkʌn.tri.saɪd/",meaning:"乡村；郊外",pos:"noun",example_en:"We spent the weekend in the countryside.",example_zh:"我们在乡村度过了周末。",topic:"自然与环境",level:"L1"},
  {id:"pet_225",word:"environment",phonetic_uk:"/ɪnˈvaɪ.rən.mənt/",phonetic_us:"/ɪnˈvaɪ.rən.mənt/",meaning:"环境",pos:"noun",example_en:"We should protect the environment.",example_zh:"我们应该保护环境。",topic:"自然与环境",level:"L1"},
  {id:"pet_226",word:"field",phonetic_uk:"/fiːld/",phonetic_us:"/fiːld/",meaning:"田野；领域",pos:"noun",example_en:"The children played in the field.",example_zh:"孩子们在田野里玩耍。",topic:"自然与环境",level:"L1"},
  {id:"pet_227",word:"forest",phonetic_uk:"/ˈfɒr.ɪst/",phonetic_us:"/ˈfɔːr.ɪst/",meaning:"森林",pos:"noun",example_en:"We went for a walk in the forest.",example_zh:"我们去森林里散了步。",topic:"自然与环境",level:"L1"},
  {id:"pet_228",word:"hill",phonetic_uk:"/hɪl/",phonetic_us:"/hɪl/",meaning:"小山；丘陵",pos:"noun",example_en:"We climbed to the top of the hill.",example_zh:"我们爬到了小山顶上。",topic:"自然与环境",level:"L1"},
  {id:"pet_229",word:"island",phonetic_uk:"/ˈaɪ.lənd/",phonetic_us:"/ˈaɪ.lənd/",meaning:"岛屿",pos:"noun",example_en:"They spent their holiday on a small island.",example_zh:"他们在一个小岛上度假。",topic:"自然与环境",level:"L1"},
  {id:"pet_230",word:"ocean",phonetic_uk:"/ˈəʊ.ʃən/",phonetic_us:"/ˈoʊ.ʃən/",meaning:"海洋",pos:"noun",example_en:"The Pacific Ocean is the largest ocean.",example_zh:"太平洋是最大的海洋。",topic:"自然与环境",level:"L1"},
  {id:"pet_231",word:"planet",phonetic_uk:"/ˈplæn.ɪt/",phonetic_us:"/ˈplæn.ɪt/",meaning:"行星",pos:"noun",example_en:"Earth is the only planet with life.",example_zh:"地球是唯一有生命的行星。",topic:"自然与环境",level:"L1"},
  {id:"pet_232",word:"pollution",phonetic_uk:"/pəˈluː.ʃən/",phonetic_us:"/pəˈluː.ʃən/",meaning:"污染",pos:"noun",example_en:"Air pollution is a serious problem in big cities.",example_zh:"空气污染是大城市的严重问题。",topic:"自然与环境",level:"L1"},
  {id:"pet_233",word:"recycle",phonetic_uk:"/ˌriːˈsaɪ.kəl/",phonetic_us:"/ˌriːˈsaɪ.kəl/",meaning:"回收利用",pos:"verb",example_en:"We should recycle paper and plastic.",example_zh:"我们应该回收纸张和塑料。",topic:"自然与环境",level:"L1"},
  {id:"pet_234",word:"river",phonetic_uk:"/ˈrɪv.ər/",phonetic_us:"/ˈrɪv.ɚ/",meaning:"河流",pos:"noun",example_en:"The river flows through the city centre.",example_zh:"这条河流经市中心。",topic:"自然与环境",level:"L1"},
  {id:"pet_235",word:"season",phonetic_uk:"/ˈsiː.zən/",phonetic_us:"/ˈsiː.zən/",meaning:"季节",pos:"noun",example_en:"My favourite season is spring.",example_zh:"我最喜欢的季节是春天。",topic:"自然与环境",level:"L1"},
  {id:"pet_236",word:"storm",phonetic_uk:"/stɔːm/",phonetic_us:"/stɔːrm/",meaning:"暴风雨",pos:"noun",example_en:"The storm caused a lot of damage.",example_zh:"暴风雨造成了很多损害。",topic:"自然与环境",level:"L1"},
  {id:"pet_237",word:"temperature",phonetic_uk:"/ˈtem.prə.tʃər/",phonetic_us:"/ˈtem.pɚ.ə.tʃɚ/",meaning:"温度",pos:"noun",example_en:"The temperature today is 30 degrees.",example_zh:"今天的气温是30度。",topic:"自然与环境",level:"L1"},
  {id:"pet_238",word:"valley",phonetic_uk:"/ˈvæl.i/",phonetic_us:"/ˈvæl.i/",meaning:"山谷",pos:"noun",example_en:"The village is located in a beautiful valley.",example_zh:"这个村庄坐落在一个美丽的山谷中。",topic:"自然与环境",level:"L1"},
  {id:"pet_239",word:"wildlife",phonetic_uk:"/ˈwaɪld.laɪf/",phonetic_us:"/ˈwaɪld.laɪf/",meaning:"野生动物",pos:"noun",example_en:"We saw lots of wildlife in the national park.",example_zh:"我们在国家公园看到了很多野生动物。",topic:"自然与环境",level:"L1"},
  {id:"pet_240",word:"wood",phonetic_uk:"/wʊd/",phonetic_us:"/wʊd/",meaning:"树林；木头",pos:"noun",example_en:"There is a small wood behind our house.",example_zh:"我们房子后面有一片小树林。",topic:"自然与环境",level:"L1"},

  // ================================================================
  // 11. DAILY LIFE (日常生活) - ~30 words
  // ================================================================
  {id:"pet_241",word:"address",phonetic_uk:"/əˈdres/",phonetic_us:"/ˈæd.res/",meaning:"地址",pos:"noun",example_en:"What's your email address?",example_zh:"你的电子邮箱地址是什么？",topic:"日常生活",level:"L1"},
  {id:"pet_242",word:"adult",phonetic_uk:"/ˈæd.ʌlt/",phonetic_us:"/əˈdʌlt/",meaning:"成年人",pos:"noun",example_en:"Children must be with an adult.",example_zh:"儿童必须有成年人陪同。",topic:"日常生活",level:"L1"},
  {id:"pet_243",word:"allow",phonetic_uk:"/əˈlaʊ/",phonetic_us:"/əˈlaʊ/",meaning:"允许",pos:"verb",example_en:"My parents don't allow me to stay up late.",example_zh:"父母不允许我熬夜。",topic:"日常生活",level:"L1"},
  {id:"pet_244",word:"apartment",phonetic_uk:"/əˈpɑːt.mənt/",phonetic_us:"/əˈpɑːrt.mənt/",meaning:"公寓",pos:"noun",example_en:"We live in a small apartment near the park.",example_zh:"我们住在公园附近的一间小公寓里。",topic:"日常生活",level:"L1"},
  {id:"pet_245",word:"arrange",phonetic_uk:"/əˈreɪndʒ/",phonetic_us:"/əˈreɪndʒ/",meaning:"安排",pos:"verb",example_en:"Can you arrange a meeting for us?",example_zh:"你能为我们安排一次会面吗？",topic:"日常生活",level:"L1"},
  {id:"pet_246",word:"available",phonetic_uk:"/əˈveɪ.lə.bəl/",phonetic_us:"/əˈveɪ.lə.bəl/",meaning:"可用的；有空的",pos:"adj",example_en:"Is this seat available?",example_zh:"这个座位有人吗？",topic:"日常生活",level:"L1"},
  {id:"pet_247",word:"avoid",phonetic_uk:"/əˈvɔɪd/",phonetic_us:"/əˈvɔɪd/",meaning:"避免",pos:"verb",example_en:"Try to avoid eating too much sugar.",example_zh:"尽量别吃太多糖。",topic:"日常生活",level:"L1"},
  {id:"pet_248",word:"bargain",phonetic_uk:"/ˈbɑː.ɡɪn/",phonetic_us:"/ˈbɑːr.ɡɪn/",meaning:"便宜货；讨价还价",pos:"noun",example_en:"This jacket was a real bargain!",example_zh:"这件夹克真是物美价廉！",topic:"日常生活",level:"L1"},
  {id:"pet_249",word:"belong",phonetic_uk:"/bɪˈlɒŋ/",phonetic_us:"/bɪˈlɑːŋ/",meaning:"属于",pos:"verb",example_en:"This book belongs to me.",example_zh:"这本书是我的。",topic:"日常生活",level:"L1"},
  {id:"pet_250",word:"celebrate",phonetic_uk:"/ˈsel.ə.breɪt/",phonetic_us:"/ˈsel.ə.breɪt/",meaning:"庆祝",pos:"verb",example_en:"How do you celebrate your birthday?",example_zh:"你怎么庆祝你的生日？",topic:"日常生活",level:"L1"},
  {id:"pet_251",word:"ceremony",phonetic_uk:"/ˈser.ɪ.mə.ni/",phonetic_us:"/ˈser.ə.moʊ.ni/",meaning:"典礼；仪式",pos:"noun",example_en:"The wedding ceremony was beautiful.",example_zh:"婚礼仪式很美。",topic:"日常生活",level:"L1"},
  {id:"pet_252",word:"challenge",phonetic_uk:"/ˈtʃæl.ɪndʒ/",phonetic_us:"/ˈtʃæl.ɪndʒ/",meaning:"挑战",pos:"noun",example_en:"Learning a new language is a challenge.",example_zh:"学习一门新语言是个挑战。",topic:"日常生活",level:"L1"},
  {id:"pet_253",word:"choice",phonetic_uk:"/tʃɔɪs/",phonetic_us:"/tʃɔɪs/",meaning:"选择",pos:"noun",example_en:"You have to make a choice.",example_zh:"你得做个选择。",topic:"日常生活",level:"L1"},
  {id:"pet_254",word:"community",phonetic_uk:"/kəˈmjuː.nə.ti/",phonetic_us:"/kəˈmjuː.nə.t̬i/",meaning:"社区",pos:"noun",example_en:"Our community is very friendly.",example_zh:"我们的社区非常友好。",topic:"日常生活",level:"L1"},
  {id:"pet_255",word:"compare",phonetic_uk:"/kəmˈpeər/",phonetic_us:"/kəmˈper/",meaning:"比较",pos:"verb",example_en:"Don't compare yourself to others.",example_zh:"不要拿自己和别人比较。",topic:"日常生活",level:"L1"},
  {id:"pet_256",word:"condition",phonetic_uk:"/kənˈdɪʃ.ən/",phonetic_us:"/kənˈdɪʃ.ən/",meaning:"条件；状况",pos:"noun",example_en:"The car is in excellent condition.",example_zh:"这辆车状况极好。",topic:"日常生活",level:"L1"},
  {id:"pet_257",word:"consider",phonetic_uk:"/kənˈsɪd.ər/",phonetic_us:"/kənˈsɪd.ɚ/",meaning:"考虑",pos:"verb",example_en:"Please consider my suggestion.",example_zh:"请考虑我的建议。",topic:"日常生活",level:"L1"},
  {id:"pet_258",word:"convenient",phonetic_uk:"/kənˈviː.ni.ənt/",phonetic_us:"/kənˈviː.ni.ənt/",meaning:"方便的",pos:"adj",example_en:"The location is very convenient for shopping.",example_zh:"这个位置购物非常方便。",topic:"日常生活",level:"L1"},
  {id:"pet_259",word:"convince",phonetic_uk:"/kənˈvɪns/",phonetic_us:"/kənˈvɪns/",meaning:"说服；使信服",pos:"verb",example_en:"I tried to convince him to come with us.",example_zh:"我试图说服他和我们一起去。",topic:"日常生活",level:"L1"},
  {id:"pet_260",word:"decorate",phonetic_uk:"/ˈdek.ə.reɪt/",phonetic_us:"/ˈdek.ə.reɪt/",meaning:"装饰",pos:"verb",example_en:"We decorated the room with balloons.",example_zh:"我们用气球装饰了房间。",topic:"日常生活",level:"L1"},
  {id:"pet_261",word:"depend",phonetic_uk:"/dɪˈpend/",phonetic_us:"/dɪˈpend/",meaning:"依赖；取决于",pos:"verb",example_en:"It depends on the weather.",example_zh:"这取决于天气。",topic:"日常生活",level:"L1"},
  {id:"pet_262",word:"describe",phonetic_uk:"/dɪˈskraɪb/",phonetic_us:"/dɪˈskraɪb/",meaning:"描述",pos:"verb",example_en:"Can you describe what you saw?",example_zh:"你能描述一下你看到了什么吗？",topic:"日常生活",level:"L1"},
  {id:"pet_263",word:"discover",phonetic_uk:"/dɪˈskʌv.ər/",phonetic_us:"/dɪˈskʌv.ɚ/",meaning:"发现",pos:"verb",example_en:"Scientists discovered a new planet.",example_zh:"科学家发现了一颗新行星。",topic:"日常生活",level:"L1"},
  {id:"pet_264",word:"enormous",phonetic_uk:"/ɪˈnɔː.məs/",phonetic_us:"/ɪˈnɔːr.məs/",meaning:"巨大的",pos:"adj",example_en:"The elephant was enormous.",example_zh:"那头大象体型巨大。",topic:"日常生活",level:"L1"},
  {id:"pet_265",word:"explain",phonetic_uk:"/ɪkˈspleɪn/",phonetic_us:"/ɪkˈspleɪn/",meaning:"解释",pos:"verb",example_en:"Can you explain this to me again?",example_zh:"你能再给我解释一遍吗？",topic:"日常生活",level:"L1"},
  {id:"pet_266",word:"habit",phonetic_uk:"/ˈhæb.ɪt/",phonetic_us:"/ˈhæb.ɪt/",meaning:"习惯",pos:"noun",example_en:"Reading before bed is a good habit.",example_zh:"睡前阅读是个好习惯。",topic:"日常生活",level:"L1"},
  {id:"pet_267",word:"identity",phonetic_uk:"/aɪˈden.tə.ti/",phonetic_us:"/aɪˈden.t̬ə.t̬i/",meaning:"身份",pos:"noun",example_en:"You need to show proof of identity.",example_zh:"你需要出示身份证明。",topic:"日常生活",level:"L1"},
  {id:"pet_268",word:"include",phonetic_uk:"/ɪnˈkluːd/",phonetic_us:"/ɪnˈkluːd/",meaning:"包括",pos:"verb",example_en:"The price includes all meals.",example_zh:"价格包含所有餐食。",topic:"日常生活",level:"L1"},
  {id:"pet_269",word:"influence",phonetic_uk:"/ˈɪn.flu.əns/",phonetic_us:"/ˈɪn.flu.əns/",meaning:"影响",pos:"noun",example_en:"Friends have a big influence on teenagers.",example_zh:"朋友对青少年有很大的影响。",topic:"日常生活",level:"L1"},
  {id:"pet_270",word:"invitation",phonetic_uk:"/ˌɪn.vɪˈteɪ.ʃən/",phonetic_us:"/ˌɪn.vəˈteɪ.ʃən/",meaning:"邀请",pos:"noun",example_en:"I received an invitation to the party.",example_zh:"我收到了派对的邀请。",topic:"日常生活",level:"L1"},

  // ================================================================
  // 12. OTHER HIGH-FREQUENCY WORDS (其他高频词) - ~30 words
  // ================================================================
  {id:"pet_271",word:"actually",phonetic_uk:"/ˈæk.tʃu.ə.li/",phonetic_us:"/ˈæk.tʃu.ə.li/",meaning:"实际上",pos:"adv",example_en:"Actually, I don't agree with that.",example_zh:"实际上，我并不同意那个。",topic:"其他高频词",level:"L1"},
  {id:"pet_272",word:"advantage",phonetic_uk:"/ədˈvɑːn.tɪdʒ/",phonetic_us:"/ədˈvæn.t̬ɪdʒ/",meaning:"优势；好处",pos:"noun",example_en:"What are the advantages of living in a city?",example_zh:"住在城市有什么好处？",topic:"其他高频词",level:"L1"},
  {id:"pet_273",word:"although",phonetic_uk:"/ɔːlˈðəʊ/",phonetic_us:"/ɑːlˈðoʊ/",meaning:"虽然",pos:"conj",example_en:"Although it was raining, we went out.",example_zh:"虽然在下雨，我们还是出去了。",topic:"其他高频词",level:"L1"},
  {id:"pet_274",word:"amount",phonetic_uk:"/əˈmaʊnt/",phonetic_us:"/əˈmaʊnt/",meaning:"数量",pos:"noun",example_en:"A small amount of salt is enough.",example_zh:"少量的盐就够了。",topic:"其他高频词",level:"L1"},
  {id:"pet_275",word:"ancient",phonetic_uk:"/ˈeɪn.ʃənt/",phonetic_us:"/ˈeɪn.ʃənt/",meaning:"古代的",pos:"adj",example_en:"We visited the ancient temple.",example_zh:"我们参观了那座古庙。",topic:"其他高频词",level:"L1"},
  {id:"pet_276",word:"attitude",phonetic_uk:"/ˈæt.ɪ.tjuːd/",phonetic_us:"/ˈæt̬.ə.tuːd/",meaning:"态度",pos:"noun",example_en:"A positive attitude is important for success.",example_zh:"积极的态度对成功很重要。",topic:"其他高频词",level:"L1"},
  {id:"pet_277",word:"benefit",phonetic_uk:"/ˈben.ɪ.fɪt/",phonetic_us:"/ˈben.ə.fɪt/",meaning:"好处；益处",pos:"noun",example_en:"Exercise has many health benefits.",example_zh:"锻炼有很多健康益处。",topic:"其他高频词",level:"L1"},
  {id:"pet_278",word:"certain",phonetic_uk:"/ˈsɜː.tən/",phonetic_us:"/ˈsɝː.tən/",meaning:"确定的；某些",pos:"adj",example_en:"I'm not certain about the answer.",example_zh:"我对答案不太确定。",topic:"其他高频词",level:"L1"},
  {id:"pet_279",word:"common",phonetic_uk:"/ˈkɒm.ən/",phonetic_us:"/ˈkɑː.mən/",meaning:"常见的；共同的",pos:"adj",example_en:"This is a very common mistake.",example_zh:"这是一个很常见的错误。",topic:"其他高频词",level:"L1"},
  {id:"pet_280",word:"communicate",phonetic_uk:"/kəˈmjuː.nɪ.keɪt/",phonetic_us:"/kəˈmjuː.nə.keɪt/",meaning:"交流；沟通",pos:"verb",example_en:"We communicate by email most days.",example_zh:"我们大多数日子通过邮件沟通。",topic:"其他高频词",level:"L1"},
  {id:"pet_281",word:"complete",phonetic_uk:"/kəmˈpliːt/",phonetic_us:"/kəmˈpliːt/",meaning:"完成；完整的",pos:"verb",example_en:"Please complete the form and sign it.",example_zh:"请填完表格并签名。",topic:"其他高频词",level:"L1"},
  {id:"pet_282",word:"difficult",phonetic_uk:"/ˈdɪf.ɪ.kəlt/",phonetic_us:"/ˈdɪf.ə.kəlt/",meaning:"困难的",pos:"adj",example_en:"The exam was more difficult than I expected.",example_zh:"考试比我预想的更难。",topic:"其他高频词",level:"L1"},
  {id:"pet_283",word:"disadvantage",phonetic_uk:"/ˌdɪs.ədˈvɑːn.tɪdʒ/",phonetic_us:"/ˌdɪs.ədˈvæn.t̬ɪdʒ/",meaning:"缺点；劣势",pos:"noun",example_en:"The main disadvantage is the cost.",example_zh:"主要缺点是成本。",topic:"其他高频词",level:"L1"},
  {id:"pet_284",word:"encourage",phonetic_uk:"/ɪnˈkʌr.ɪdʒ/",phonetic_us:"/ɪnˈkɝː.ɪdʒ/",meaning:"鼓励",pos:"verb",example_en:"My teacher encouraged me to try again.",example_zh:"老师鼓励我再试一次。",topic:"其他高频词",level:"L1"},
  {id:"pet_285",word:"especially",phonetic_uk:"/ɪˈspeʃ.əl.i/",phonetic_us:"/ɪˈspeʃ.əl.i/",meaning:"尤其；特别",pos:"adv",example_en:"I love fruit, especially strawberries.",example_zh:"我喜欢水果，尤其是草莓。",topic:"其他高频词",level:"L1"},
  {id:"pet_286",word:"evidence",phonetic_uk:"/ˈev.ɪ.dəns/",phonetic_us:"/ˈev.ə.dəns/",meaning:"证据",pos:"noun",example_en:"There is no evidence that he did it.",example_zh:"没有证据表明是他做的。",topic:"其他高频词",level:"L1"},
  {id:"pet_287",word:"imagine",phonetic_uk:"/ɪˈmædʒ.ɪn/",phonetic_us:"/ɪˈmædʒ.ɪn/",meaning:"想象",pos:"verb",example_en:"Imagine you could fly anywhere in the world.",example_zh:"想象一下你可以飞到世界任何地方。",topic:"其他高频词",level:"L1"},
  {id:"pet_288",word:"improve",phonetic_uk:"/ɪmˈpruːv/",phonetic_us:"/ɪmˈpruːv/",meaning:"改进；提高",pos:"verb",example_en:"I want to improve my English.",example_zh:"我想提高我的英语。",topic:"其他高频词",level:"L1"},
  {id:"pet_289",word:"increase",phonetic_uk:"/ɪnˈkriːs/",phonetic_us:"/ɪnˈkriːs/",meaning:"增加",pos:"verb",example_en:"The population continues to increase.",example_zh:"人口持续增长。",topic:"其他高频词",level:"L1"},
  {id:"pet_290",word:"opinion",phonetic_uk:"/əˈpɪn.jən/",phonetic_us:"/əˈpɪn.jən/",meaning:"意见；看法",pos:"noun",example_en:"In my opinion, this is the best choice.",example_zh:"在我看来，这是最好的选择。",topic:"其他高频词",level:"L1"},
  {id:"pet_291",word:"particular",phonetic_uk:"/pəˈtɪk.jə.lər/",phonetic_us:"/pɚˈtɪk.jə.lɚ/",meaning:"特别的；特定的",pos:"adj",example_en:"Is there a particular reason?",example_zh:"有什么特别的原因吗？",topic:"其他高频词",level:"L1"},
  {id:"pet_292",word:"recognise",phonetic_uk:"/ˈrek.əɡ.naɪz/",phonetic_us:"/ˈrek.əɡ.naɪz/",meaning:"认出；识别",pos:"verb",example_en:"I didn't recognise him at first.",example_zh:"我一开始没认出他来。",topic:"其他高频词",level:"L1"},
  {id:"pet_293",word:"responsible",phonetic_uk:"/rɪˈspɒn.sə.bəl/",phonetic_us:"/rɪˈspɑːn.sə.bəl/",meaning:"负责的",pos:"adj",example_en:"You need to be responsible for your actions.",example_zh:"你需要对自己的行为负责。",topic:"其他高频词",level:"L1"},
  {id:"pet_294",word:"solution",phonetic_uk:"/səˈluː.ʃən/",phonetic_us:"/səˈluː.ʃən/",meaning:"解决方案；答案",pos:"noun",example_en:"We need to find a solution to this problem.",example_zh:"我们需要找到这个问题的解决方案。",topic:"其他高频词",level:"L1"},
  {id:"pet_295",word:"spread",phonetic_uk:"/spred/",phonetic_us:"/spred/",meaning:"传播；扩散",pos:"verb",example_en:"The news spread quickly around the school.",example_zh:"消息迅速传遍了学校。",topic:"其他高频词",level:"L1"},
  {id:"pet_296",word:"support",phonetic_uk:"/səˈpɔːt/",phonetic_us:"/səˈpɔːrt/",meaning:"支持",pos:"verb",example_en:"My family always supports me.",example_zh:"我的家人总是支持我。",topic:"其他高频词",level:"L1"},
  {id:"pet_297",word:"throughout",phonetic_uk:"/θruːˈaʊt/",phonetic_us:"/θruːˈaʊt/",meaning:"遍及；贯穿",pos:"prep",example_en:"The museum is open throughout the year.",example_zh:"博物馆全年开放。",topic:"其他高频词",level:"L1"},
  {id:"pet_298",word:"towards",phonetic_uk:"/təˈwɔːdz/",phonetic_us:"/tɔːrdz/",meaning:"朝着；向着",pos:"prep",example_en:"He walked towards the door.",example_zh:"他朝门口走去。",topic:"其他高频词",level:"L1"},
  {id:"pet_299",word:"various",phonetic_uk:"/ˈveə.ri.əs/",phonetic_us:"/ˈver.i.əs/",meaning:"各种各样的",pos:"adj",example_en:"We discussed various topics in class.",example_zh:"我们在课上讨论了各种各样的话题。",topic:"其他高频词",level:"L1"},
  {id:"pet_300",word:"worried",phonetic_uk:"/ˈwʌr.id/",phonetic_us:"/ˈwɝː.id/",meaning:"担心的",pos:"adj",example_en:"I'm worried about the test tomorrow.",example_zh:"我担心明天的考试。",topic:"其他高频词",level:"L1"}
];

// Topic list with Chinese labels
const PET_TOPICS = [
  "全部话题",
  "服饰与配饰",
  "通讯与科技",
  "教育",
  "娱乐与媒体",
  "食物与饮料",
  "健康与运动",
  "旅行与交通",
  "情感与性格",
  "职业与工作",
  "自然与环境",
  "日常生活",
  "其他高频词"
];
